### ISSUE TITLE
Raise error when plugins aren't installed

### ISSUE THREAD

**Issue by jverdeyen** [yappabe/vagrant-docker#10]
Should we raise an error message when required vagrant plugins aren't installed?

```
unless Vagrant.has_plugin?("vagrant-some-plugin")
  raise 'some-plugin is not installed!'
end
```

We need the vagrant-triggers plugin to add routes.

@veloxy

**Comment by veloxy** [comment]
Better display an error than leave people guessing! :+1:

**Comment by jverdeyen** [comment]
Solved by https://github.com/yappabe/vagrant-docker/pull/18
